### ISSUE TITLE
Make global test timeout configurable (not hardcoded)

### ISSUE THREAD

**Issue by t-moe** [probe-rs/embedded-test#3]

**Comment by bugadani** [comment]
What do you think about making this a property of `#[embedded_test::tests]`, like `#[embedded_test::tests(default_timeout = 15)]`?

**Comment by t-moe** [comment]
I like the way to specify the default timeout (`#[embedded_test::tests(default_timeout = 15)]`). 

Initially I thought we should pass the default to the host, so that we can also override the default via command line argument. But we can still do that later if needed 👍
