### ISSUE TITLE
Running embedded-test on RP2040 (rp-rs) targets

### ISSUE THREAD

**Issue by murraytodd** [probe-rs/embedded-test#39]
I've tried to follow the instructions to add a simple do-nothing unit test to a minimal `rp2040` "blinky" program. I have everything I did available for review [here on github](https://github.com/murraytodd/rp2040-blinky/tree/testing). The specific changes I made to try to implement `embedded-test` can be seen [in this commit](https://github.com/murraytodd/rp2040-blinky/commit/def0ea7ebc30b662bd89053c812a06d4e5fa63d4).

When I try to execute `cargo test --test blinky_test` I get some hairy "error: linking with `flip-link` failed: exit status: 1" error with the full output available in this attachment:

[err.txt](https://github.com/user-attachments/files/16822073/err.txt)

**Comment by t-moe** [comment]
The error message indicates that you are missing default interrupt/exception handlers. (An error not related to embedded-test)

 I dont know the rp hal, but 
sometimes its enough to add something like `use rp2050_hal as _`.
